version: 2
# this is required to reference the source tables in the models
sources:
  - name: bronze
    schema: bronze
    tables:
       - name : airbnb_listings_raw
       - name : 'g01'
       - name : 'g02'
       - name : lga_suburb
       - name : nsw_lga_code